<template>
	<scroll-view style="min-height: 100%; padding: 15px;box-sizing: border-box;">
		<view class="welcome focus-in-expand-fwd">Welcome Nixi</view>
		
		<!-- #ifndef H5 -->
		<fix-window />
		<!-- #endif -->
	</scroll-view>
</template>

<script>
	import {
		version
	} from '../../package.json'

	export default {
		data() {
			return {
				adminVersion: version,
			}
		},
		watch: {

		},
		onLoad() {},
	}
</script>
<style lang="scss" scoped>
	.welcome{
		height: 80vh;
		font-size: 120rpx;
		font-weight: bold;
		display: flex;
		align-items: center;
		justify-content: center;
	}
	.focus-in-expand-fwd {
		-webkit-animation: focus-in-expand-fwd 2s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
		        animation: focus-in-expand-fwd 2s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	}
	/* ----------------------------------------------
	 * Generated by Animista on 2022-7-17 6:41:40
	 * Licensed under FreeBSD License.
	 * See http://animista.net/license for more info. 
	 * w: http://animista.net, t: @cssanimista
	 * ---------------------------------------------- */
	
	/**
	 * ----------------------------------------
	 * animation focus-in-expand-fwd
	 * ----------------------------------------
	 */
	@-webkit-keyframes focus-in-expand-fwd {
	  0% {
	    letter-spacing: -0.5em;
	    -webkit-transform: translateZ(-800px);
	            transform: translateZ(-800px);
	    -webkit-filter: blur(12px);
	            filter: blur(12px);
	    opacity: 0;
	  }
	  100% {
	    -webkit-transform: translateZ(0);
	            transform: translateZ(0);
	    -webkit-filter: blur(0);
	            filter: blur(0);
	    opacity: 1;
	  }
	}
	@keyframes focus-in-expand-fwd {
	  0% {
	    letter-spacing: -0.5em;
	    -webkit-transform: translateZ(-800px);
	            transform: translateZ(-800px);
	    -webkit-filter: blur(12px);
	            filter: blur(12px);
	    opacity: 0;
	  }
	  100% {
	    -webkit-transform: translateZ(0);
	            transform: translateZ(0);
	    -webkit-filter: blur(0);
	            filter: blur(0);
	    opacity: 1;
	  }
	}


</style>
<style>
	/* #ifndef H5 */
	page {
		padding-top: 85px;
	}
	/* #endif */
</style>
