<template>
	<scroll-view scroll-y style="width:100%;height:80vh;">
		<!-- #ifndef H5 -->
		<fix-window />
		<!-- #endif -->
		<qiun-data-charts type="word" :opts="opts" :chartData="chartData" />
		<!-- <view class="welcome focus-in-expand-fwd">Welcome Nixi</view> -->

	</scroll-view>
</template>

<script>
	import {
		version
	} from '../../package.json'

	export default {
		data() {
			return {
				adminVersion: version,
				chartData: {},
				opts: {
					color: ["#1890FF", "#91CB74", "#FAC858", "#EE6666", "#73C0DE", "#3CA272", "#FC8452", "#9A60B4",
						"#ea7ccc"
					],
					padding: undefined,
					extra: {
						word: {
							type: "normal",
							autoColors: false
						}
					}
				}
			}
		},
		watch: {

		},
		onLoad() {
			this.$nextTick(() => {
				this.initChart()
			})
		},
		methods: {
			initChart() {
				setTimeout(() => {
					//模拟服务器返回数据，如果数据格式和标准格式不同，需自行按下面的格式拼接
					let res = {
						series: [{
								name: "Welcome",
								textSize: 60,
								data: undefined
							},
							{
								name: "Nixi",
								textSize: 50,
								data: undefined
							},
							{
								name: "匿习",
								textSize: 50,
								data: undefined
							},
							{
								name: "欢迎使用",
								textSize: 50,
								data: undefined
							},
							{
								name: "感谢",
								textSize: 50,
								data: undefined
							},
							{
								name: "栓Q",
								textSize: 40,
								data: undefined
							},
							{
								name: "大数据",
								textSize: 36,
								data: undefined
							},
							{
								name: "前端",
								textSize: 40,
								data: undefined
							},
							{
								name: "JavaScript",
								textSize: 40,
								data: undefined
							},
							{
								name: "scss",
								textSize: 36,
								data: undefined
							},
							{
								name: "css",
								textSize: 40,
								data: undefined
							},
							{
								name: "es6",
								textSize: 36,
								data: undefined
							},
							{
								name: "Vue",
								textSize: 40,
								data: undefined
							},
							{
								name: "angular",
								textSize: 36,
								data: undefined
							},
							{
								name: "react",
								textSize: 40,
								data: undefined
							},
							{
								name: "uniapp",
								textSize: 36,
								data: undefined
							}
						]
					};
					this.chartData = JSON.parse(JSON.stringify(res));
				}, 500);
			}
		}
	}
</script>
<style lang="scss" scoped>


	.focus-in-expand-fwd {
		-webkit-animation: focus-in-expand-fwd 2s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
		animation: focus-in-expand-fwd 2s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	}

	/* ----------------------------------------------
	 * Generated by Animista on 2022-7-17 6:41:40
	 * Licensed under FreeBSD License.
	 * See http://animista.net/license for more info. 
	 * w: http://animista.net, t: @cssanimista
	 * ---------------------------------------------- */

	/**
	 * ----------------------------------------
	 * animation focus-in-expand-fwd
	 * ----------------------------------------
	 */
	@-webkit-keyframes focus-in-expand-fwd {
		0% {
			letter-spacing: -0.5em;
			-webkit-transform: translateZ(-800px);
			transform: translateZ(-800px);
			-webkit-filter: blur(12px);
			filter: blur(12px);
			opacity: 0;
		}

		100% {
			-webkit-transform: translateZ(0);
			transform: translateZ(0);
			-webkit-filter: blur(0);
			filter: blur(0);
			opacity: 1;
		}
	}

	@keyframes focus-in-expand-fwd {
		0% {
			letter-spacing: -0.5em;
			-webkit-transform: translateZ(-800px);
			transform: translateZ(-800px);
			-webkit-filter: blur(12px);
			filter: blur(12px);
			opacity: 0;
		}

		100% {
			-webkit-transform: translateZ(0);
			transform: translateZ(0);
			-webkit-filter: blur(0);
			filter: blur(0);
			opacity: 1;
		}
	}
</style>
<style>
	/* #ifndef H5 */
	page {
		padding-top: 85px;
	}

	/* #endif */
</style>
